"""empty message

Revision ID: 177fe32ba3e2
Revises: deba56ffc7e2
Create Date: 2020-08-16 23:15:13.700099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177fe32ba3e2'
down_revision = 'deba56ffc7e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('micro_blog_post', schema=None) as batch_op:
        batch_op.drop_column('isEdited')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('micro_blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isEdited', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
