"""empty message

Revision ID: 24786aec539e
Revises: 83d3933ed352
Create Date: 2020-08-14 14:28:23.413465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24786aec539e'
down_revision = '83d3933ed352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carousel_post')
    op.drop_column('comment', 'carousel_pid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('carousel_pid', sa.INTEGER(), nullable=True))
    op.create_table('carousel_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_type', sa.VARCHAR(), nullable=True),
    sa.Column('post_id', sa.VARCHAR(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('created_on', sa.VARCHAR(), nullable=True),
    sa.Column('images', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
