"""empty message

Revision ID: 49317585f5ee
Revises: 24786aec539e
Create Date: 2020-08-14 14:34:28.027752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49317585f5ee'
down_revision = '24786aec539e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'carousel_post', ['carousel_pid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
