"""empty message

Revision ID: 83d3933ed352
Revises: c584cfbb9bdb
Create Date: 2020-08-14 13:32:32.271486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d3933ed352'
down_revision = 'c584cfbb9bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('carousel_pid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'carousel_post', ['carousel_pid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'carousel_pid')
    # ### end Alembic commands ###
