"""empty message

Revision ID: 9a80089036cc
Revises: 
Create Date: 2020-08-12 18:58:20.213713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a80089036cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voted_polls')
    op.add_column('user', sa.Column('basepoints', sa.String(), nullable=True))
    op.add_column('user', sa.Column('secondarypoints', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'secondarypoints')
    op.drop_column('user', 'basepoints')
    op.create_table('voted_polls',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('selected_option', sa.INTEGER(), nullable=True),
    sa.Column('poll_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
