"""empty message

Revision ID: c584cfbb9bdb
Revises: 9a80089036cc
Create Date: 2020-08-12 19:07:33.403060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c584cfbb9bdb'
down_revision = '9a80089036cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'website')
    # ### end Alembic commands ###
