"""First Migrate

Revision ID: d0449479cd72
Revises: 
Create Date: 2020-08-16 23:05:37.078179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0449479cd72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_comment_carousel_pid_carousel_post'), 'carousel_post', ['carousel_pid'], ['id'])

    with op.batch_alter_table('micro_blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isEdited', sa.Boolean(), nullable=True))

    with op.batch_alter_table('reshare_with_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isEdited', sa.Boolean(), nullable=True))

    with op.batch_alter_table('shareable_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isEdited', sa.Boolean(), nullable=True))

    with op.batch_alter_table('timeline_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isEdited', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_post', schema=None) as batch_op:
        batch_op.drop_column('isEdited')

    with op.batch_alter_table('shareable_post', schema=None) as batch_op:
        batch_op.drop_column('isEdited')

    with op.batch_alter_table('reshare_with_comment', schema=None) as batch_op:
        batch_op.drop_column('isEdited')

    with op.batch_alter_table('micro_blog_post', schema=None) as batch_op:
        batch_op.drop_column('isEdited')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_carousel_pid_carousel_post'), type_='foreignkey')

    # ### end Alembic commands ###
