"""empty message

Revision ID: deba56ffc7e2
Revises: 9af8d33b3629
Create Date: 2020-08-16 23:13:54.243928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deba56ffc7e2'
down_revision = '9af8d33b3629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('micro_blog_post', 'isEdited')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('micro_blog_post', sa.Column('isEdited', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
